In [8]:
import numpy as np
vetor = np.array([1, 2, 3])
matrix = np.array([[1,2,3.0],[4,5,6]])
print(vetor)
print(matrix)

# 维度 （行，lie）
print(vetor.shape)
print(matrix.shape)

# 元素个数
print(vetor.size)
print(matrix.size)

# 访问元素 
print(vetor[2])
print(matrix[1,2])

print(matrix.dtype)

[1 2 3]
[[1. 2. 3.]
 [4. 5. 6.]]
(3,)
(2, 3)
3
6
3
6.0
float64


In [20]:
# numpy读取数据
import numpy
people = numpy.genfromtxt("test2_numpy.txt" , delimiter="\t" , dtype = str , skip_header = 1 , encoding="utf-8")
print(people)
print(people[1:5 , 1]) # 访问第二列的第2-5行第二列的数据
print(people[1:5 ,:]) # 访问第1-4行的数据
print(people[:,1]) # 访问第二列的所有数据


[['2018' '陈明' '软件工程师']
 ['2019' '李雪' '小学教师']
 ['2020' '张伟' '护士']
 ['2021' '王芳' '会计']
 ['2022' '刘洋' '设计师']
 ['2023' '陈静' '销售经理']
 ['2024' '赵强' '司机']
 ['2020' '周敏' '人力资源专员']
 ['2019' '吴浩' '厨师']
 ['2025' '郑丽' '文案编辑']]
['李雪' '张伟' '王芳' '刘洋']
[['2019' '李雪' '小学教师']
 ['2020' '张伟' '护士']
 ['2021' '王芳' '会计']
 ['2022' '刘洋' '设计师']]
['陈明' '李雪' '张伟' '王芳' '刘洋' '陈静' '赵强' '周敏' '吴浩' '郑丽']


In [44]:
# numpy向量运算

import numpy as np
vetor = np.array([1, 2, 3])

vetor1 = vetor + 1  #直接进行加减乘除运算
vetor2 = 2*vetor
vetor3 = vetor*vetor
vetor4 = vetor.dot(vetor) #点积

vetor5 = vetor * vetor.T #

vetor6 = vetor + np.arange(3)
vetor7 = vetor + 1
print(vetor1)
print(vetor2)
print(vetor3)
print(vetor4)
print(vetor5)
print(vetor6)
print(vetor7)

vetor == 2


[2 3 4]
[2 4 6]
[1 4 9]
14
[1 4 9]
[1 3 5]
[2 3 4]


array([False,  True, False])

In [ ]:
# numpy矩阵运算

import numpy

matrix = numpy.array([[1,3,5] , [2,4,6] , [7,8,9]])

matrix0 = matrix.transpose()
matrix00 = matrix.T  #转置 .T 或者 .transpose() 都可以
matrix1 = matrix + matrix
matrix2 = matrix * 2
matrix3 = matrix * matrix
matrix4 = matrix * matrix0  # 矩阵相乘是对应项相乘  
matrix5 = matrix.dot(matrix0) # .dot才是矩阵乘法，内积
print(matrix0)
print(matrix00)
print(matrix1)
print(matrix2)
print(matrix3)
print(matrix4)
print(matrix5)

[[1 2 7]
 [3 4 8]
 [5 6 9]]
[[1 2 7]
 [3 4 8]
 [5 6 9]]
[[ 2  6 10]
 [ 4  8 12]
 [14 16 18]]
[[ 2  6 10]
 [ 4  8 12]
 [14 16 18]]
[[ 1  9 25]
 [ 4 16 36]
 [49 64 81]]
[[ 1  6 35]
 [ 6 16 48]
 [35 48 81]]
[[ 35  44  76]
 [ 44  56 100]
 [ 76 100 194]]


In [14]:
# 逻辑运算与或非

import numpy as np
vetor = np.array([1, 2, 3])

print((vetor == 2) & (vetor > 2)) # 逻辑与
print((vetor ==2) | (vetor > 2)) # 逻辑或
print(~(vetor == 2)) # 逻辑非




[False False False]
[False  True  True]
[ True False  True]


In [ ]:
# 类型转换

import numpy as np
vetor = np.array(["12", "2", "3"])  # U代表字符串类型
print(vetor.dtype)

vetor = vetor.astype(float)
print(vetor)
print(vetor.dtype)


<U2
[12.  2.  3.]
float64


In [ ]:
import numpy
matrix = numpy.array([[1,2,3] , [4,5,6] , [7,8,9] , [10,11,12]])
print(matrix.size)
print(matrix.shape)

print(matrix.max() , matrix.min() , matrix.mean() , matrix.sum())
print(matrix.mean(axis=0)) # 按列求平均值
print(matrix.max(axis = 1)) # 按行求最大值

vector = np.array([1,2,3])
weight = np.array([0.1 , 0.3 , 0.6])
result = np.average(vector , weights=weight) # 加权平均值.average函数可以计算加权平均值,但是他是顶层函数，调用时要np.average(数组，权重)，weights参数指定权重。
print(result)

12
(4, 3)
12 1 6.5 78
[5.5 6.5 7.5]
[ 3  6  9 12]
2.5


In [ ]:
import numpy 
print(np.arange(0 , 10 , 2)) # arange函数可以生成一个等差数列，参数分别是起始值，结束值，步长。注意结束值不包含在内。

a = np.arange(0 , 12 , 2).reshape(3,2) # reshape函数可以改变数组的形状，参数是一个元组，表示新的形状。这里将一维数组变成了3行2列的二维数组。
print(a)

[0 2 4 6 8]
[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [31]:
import numpy 

a = np.arange(0 , 50 , 5).reshape(2,5) # reshape函数可以改变数组的形状，参数是一个元组，表示新的形状。这里将一维数组变成了3行2列的二维数组。
print(a)

print(a.ndim) # ndim属性可以查看数组的维度
print(a.dtype) # dtype属性可以查看数组的元素类型

[[ 0  5 10 15 20]
 [25 30 35 40 45]]
2
int64


In [ ]:
import numpy as np
print(np.zeros((3 ,4))) # zeros函数可以生成一个全是0的数组，参数是一个元组，表示数组的形状。这里生成了一个3行4列的二维数组。
print(np.ones((2,3,5))) # ones函数可以生成一个全是1的数组，参数是一个元组，表示数组的形状。这里生成了一个2个3行5列的三维数组。
print(np.full((2,4) , "dog")) # full函数可以生成一个全是指定值的数组，参数是一个元组，表示数组的形状，第二个参数是指定的值。这里生成了一个2行4列的二维数组，元素都是字符串"dog"。


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[['dog' 'dog' 'dog' 'dog']
 ['dog' 'dog' 'dog' 'dog']]


In [42]:
import numpy as np
import random

a = np.random.randint(0 , 100 , (3,4)) # np.random.randint函数可以生成一个指定范围内的随机整数，参数分别是起始值，结束值，数组的形状。这里生成了一个3行4列的二维数组，元素是0-99之间的随机整数。
print(a)

b = random.randint(0 , 100) # random.randint函数可以生成一个指定范围内的随机整数，参数分别是起始值和结束值。这里生成了一个0-99之间的随机整数。
print(b)

print(a > b)

c = np.random.random((2,3))
print(c) # np.random.random函数可以生成一个指定形状的数组，元素是0-1之间的随机小数。参数是一个元组，表示数组的形状。这里生成了一个2行3列的二维数组。

d = np.linspace(0 , 2*np.pi , 10) # np.linspace函数可以生成一个指定范围内的等差数列，参数分别是起始值，结束值，元素个数。这里生成了一个0-2π之间的等差数列，包含10个元素。
print(d)

e = np.sin(d) # np.sin函数可以计算数组中每个元素的正弦值。参数是一个数组。这里计算了d数组中每个元素的正弦值。
print(e)

[[76  4 45 70]
 [44  1 47 96]
 [22 25 16 48]]
44
[[ True False  True  True]
 [False False  True  True]
 [False False False  True]]
[[0.79459239 0.26278635 0.37176539]
 [0.73706914 0.40524714 0.87876097]]
[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]
[ 0.00000000e+00  6.42787610e-01  9.84807753e-01  8.66025404e-01
  3.42020143e-01 -3.42020143e-01 -8.66025404e-01 -9.84807753e-01
 -6.42787610e-01 -2.44929360e-16]


In [55]:
a = np.arange(2,11).reshape(3,3)
b = np.arange(0,9).reshape(3,3)
print(a*b)
print(a.dot(b))
print(np.dot(a,b))
print("-"*30)

print(np.exp(a)) # np.exp函数可以计算数组中每个元素的指数值。参数是一个数组。这里计算了a数组中每个元素的指数值。
print("-"*30)

print(np.sqrt(b))# np.sqrt函数可以计算数组中每个元素的平方根。参数是一个数组。这里计算了b数组中每个元素的平方根。
print("-"*30)




[[ 0  3  8]
 [15 24 35]
 [48 63 80]]
[[ 33  42  51]
 [ 60  78  96]
 [ 87 114 141]]
[[ 33  42  51]
 [ 60  78  96]
 [ 87 114 141]]
------------------------------
[[7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04]]
------------------------------
[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]
------------------------------


In [56]:
c = np.floor(10*np.random.random((2,3)))
print(c) # np.floor函数可以对数组中每个元素进行向下取整。参数是一个数组。这里生成了一个2行3列的二维数组，元素是0-10之间的随机小数，然后对每个元素进行向下取整。
print(c.dtype)
print("-"*30)

print(c.ravel()) # np.ravel函数可以将多维数组展平为一维数组。参数是一个数组。这里将c数组展平为一维数组。
print("-"*30)

print(c.reshape(3,2)) # np.reshape函数可以改变数组的形状，参数是一个元组，表示新的形状。这里将c数组变成了3行2列的二维数组。
print("-"*30)
c.shape = (3,2) # 也可以直接修改shape属性来改变数组的形状。这里将c数组变成了3行2列的二维数组。
print(c)

[[4. 1. 3.]
 [5. 1. 7.]]
float64
------------------------------
[4. 1. 3. 5. 1. 7.]
------------------------------
[[4. 1.]
 [3. 5.]
 [1. 7.]]
------------------------------
[[4. 1.]
 [3. 5.]
 [1. 7.]]


In [60]:
d = np.floor(10*np.random.random((2,3)))
print(d)

e = np.random.randint(0 , 10 , (2,3))
print(e)
print("-"*30)

print(np.vstack((d,e))) # np.vstack函数可以将多个数组按垂直方向进行拼接。参数是一个元组，表示要拼接的数组。这里将d和e两个2行3列的二维数组按垂直方向进行拼接，得到一个4行3列的二维数组。
print("-"*30)

print(np.hstack((d,e))) # np.hstack函数可以将多个数组按水平方向进行拼接。参数是一个元组，表示要拼接的数组。这里将d和e两个2行3列的二维数组按水平方向进行拼接，得到一个2行6列的二维数组。

[[1. 0. 5.]
 [7. 1. 6.]]
[[1 3 8]
 [1 5 7]]
------------------------------
[[1. 0. 5.]
 [7. 1. 6.]
 [1. 3. 8.]
 [1. 5. 7.]]
------------------------------
[[1. 0. 5. 1. 3. 8.]
 [7. 1. 6. 1. 5. 7.]]


In [64]:
a = np.random.randint(0 , 10 , (2,8))
print(a)
print("*"*30)

print(np.hsplit(a , 4)) # np.hsplit函数可以将一个数组按水平方向进行分割。参数分别是要分割的数组和分割的份数。这里将a数组按水平方向分成4份，每份是一个2行2列的二维数组。
print("*"*30)

print(np.vsplit(a , 2)) # np.vsplit函数可以将一个数组按垂直方向进行分割。参数分别是要分割的数组和分割的份数。这里将a数组按垂直方向分成2份，每份是一个1行8列的二维数组。
print("*"*30)

print(np.hsplit(a , (1,3,7))) # np.hsplit函数也可以指定分割的位置，参数分别是要分割的数组和一个元组，表示分割的位置。这里将a数组按水平方向在第1列、第3列和第7列进行分割，得到4个二维数组，分别是a[:, :1]、a[:, 1:3]、a[:, 3:7]和a[:, 7:]。

[[4 4 8 2 8 2 4 9]
 [9 1 9 9 3 0 6 7]]
******************************
[array([[4, 4],
       [9, 1]], dtype=int32), array([[8, 2],
       [9, 9]], dtype=int32), array([[8, 2],
       [3, 0]], dtype=int32), array([[4, 9],
       [6, 7]], dtype=int32)]
******************************
[array([[4, 4, 8, 2, 8, 2, 4, 9]], dtype=int32), array([[9, 1, 9, 9, 3, 0, 6, 7]], dtype=int32)]
******************************
[array([[4],
       [9]], dtype=int32), array([[4, 8],
       [1, 9]], dtype=int32), array([[2, 8, 2, 4],
       [9, 3, 0, 6]], dtype=int32), array([[9],
       [7]], dtype=int32)]


In [68]:
a = np.random.randint(0 , 10 , (2,8))
print(a)
print("*"*30)

b = a.T
print(b) # 转置
print("*"*30    )

print(b.sum(axis=0)) # 按列求和
print("*"*30)

print(np.vsplit(b , (3,5))) 

[[3 2 9 2 0 8 1 5]
 [2 5 1 0 3 1 8 3]]
******************************
[[3 2]
 [2 5]
 [9 1]
 [2 0]
 [0 3]
 [8 1]
 [1 8]
 [5 3]]
******************************
[30 23]
******************************
[array([[3, 2],
       [2, 5],
       [9, 1]], dtype=int32), array([[2, 0],
       [0, 3]], dtype=int32), array([[8, 1],
       [1, 8],
       [5, 3]], dtype=int32)]


In [79]:
a = np.arange(0 , 10 ) # arange函数可以生成一个等差数列，参数分别是起始值，结束值，步长。注意结束值不包含在内。这里生成了一个0-9之间的等差数列。
print(a)

# a.shape = (2 ,5)
# print(a)
print("*"*30)

b = a
print(b)

b.shape = (2,5) # 修改b的形状，a的形状也会改变，因为a和b指向同一个数组对象。
print(b)
print("-"*30)
print(a)

print(id(a))
print(id(b))

[0 1 2 3 4 5 6 7 8 9]
******************************
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
[[0 1 2 3 4]
 [5 6 7 8 9]]
3021513986224
3021513986224


In [ ]:
c = a.view() # view方法可以创建一个新的视图对象，指向同一个数组数据。修改c的形状不会影响a和b的形状。

c.shape = (5,2)

c[1,1] = 100# 修改c的元素，ab的形状不会变，但是a和b的元素也会改变，因为c和a、b指向同一个数组数据。
print(c)
print("-"*30)

print(a)

print("-"*30)
print(id(a))
print(id(c))    



[[  0   1   2 100   4]
 [  5   6   7   8   9]]
[[  0   1]
 [  2 100]
 [  4   5]
 [  6   7]
 [  8   9]]
------------------------------
[[  0   1   2 100   4]
 [  5   6   7   8   9]]
------------------------------
3021513986128
3021513834192


In [ ]:
d = a.copy() # copy方法可以创建一个新的数组对象，复制原数组的数据。修改d的形状和元素都不会影响a、b、c。
d.shape = (10,1)
d[0,0] = 1000
print(d)
print("-"*30)
print(c)
print(a)
print(id(a))
print(id(d))

[[1000]
 [   1]
 [   2]
 [   3]
 [   4]
 [   5]
 [   6]
 [   7]
 [   8]
 [   9]]
------------------------------
[[0 1 2 3 4]
 [5 6 7 8 9]]
3021513986224
3021513987952


In [83]:
a = np.random.randint(0,100 , (4,5))
print(a)

print("-"*30)
maxindex = np.argmax(a , axis = 0) # np.argmax函数可以返回数组中最大值的索引，参数是一个数组。这里返回了a数组中每列最大值的索引。

print(maxindex)

[[36 24 23 63 77]
 [83 40 84 13 74]
 [42  7 80 59  8]
 [79 60 19 79 24]]
------------------------------
[1 3 1 3 0]
